### ISSUE TITLE
Add printing help documentation to print toolbar

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/airbranch-reports#51]
An "information" button 🛈 next to the print button can be clicked to show helpful info, such as how to print or save a PDF using the browser tools and how to hide the date/url headers and footers on the printout.

**Comment by patdnr** [comment]
Instead of creating an "information" button, I opted to display the instruction when the user hovers over the print button.

An interesting thing here is that the font on the pages are different from each other (pic below). I think this is because I set the font-size as 1rem.

stack-test:
<img width="955" alt="stack-test" src="https://user-images.githubusercontent.com/113926513/208029939-fe09866f-3198-4276-a4ee-c938a249b835.png">

acc-report:
<img width="958" alt="acc-report" src="https://user-images.githubusercontent.com/113926513/208029955-c91d208b-56a5-43f8-a5df-48cc0eaa55b7.png">

**Comment by dougwaldron** [comment]
The tooltip is picking up "font-family" from the "body" or "body.sans-serif" selectors at the top of "report.css". 

Further down in the css file, the ".print-toolbar button" is set to "font-family: system-ui;" Move that property up a few lines to ".print-toolbar" instead and all should be good.

**Comment by dougwaldron** [comment]
Also, instead of using JavaScript, you can do this in CSS with a sibling selector:

```css
#print-button:hover + #tooltip-text, #print-button:focus + #tooltip-text {
    display: block;
}
```

That gives you keyboard accessibility too.

**Comment by patdnr** [comment]
> ```css
> #print-button:hover + #tooltip-text, #print-button:focus + #tooltip-text {
>     display: block;
> }
> ```

I tested this and it did not work.

**Comment by dougwaldron** [comment]
> I tested this and it did not work.

Double check the specificity of your selectors. `p#tooltip-text` will override `#tooltip-text`. Both selectors should match for the hover to take effect.
